steps:
  - name: 'alpine'
    id: 'diagnostic'
    args: ['echo', 'READING_CUSTOM_CLOUDBUILD_YAML']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA'
      - '-f'
      - 'backend-go/Dockerfile'
      - 'backend-go'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run services update $_SERVICE_NAME \
          --region=$_DEPLOY_REGION \
          --update-annotations=run.googleapis.com/sources=null \
          --quiet || true
        gcloud run deploy $_SERVICE_NAME \
          --image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA \
          --region=$_DEPLOY_REGION \
          --platform=$_PLATFORM \
          --allow-unauthenticated

images:
  - '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
