// scripts/generate-rls-audit-migration.ts
// Emits RLS hardening SQL to stdout. Human reviews + pastes into
// supabase/migrations/20261001000003_phase_a_not_null_and_rls.sql
//
// Usage: npx tsx scripts/generate-rls-audit-migration.ts > /tmp/rls-block.sql
import { Client } from 'pg';
import { readFileSync } from 'fs';
import { parse as parseYaml } from 'yaml';

const CONFIG_PATH = 'scripts/rls-audit-config.yaml';
const DB_URL = process.env.SUPABASE_DB_URL ?? 'postgresql://postgres:postgres@localhost:54322/postgres';

interface Override { category: 'T' | 'G' | 'P' | 'A' | 'S' | 'skip'; reason?: string }
interface Config { overrides: Record<string, Override> }

async function main() {
  const config: Config = parseYaml(readFileSync(CONFIG_PATH, 'utf8'));
  const client = new Client({ connectionString: DB_URL });
  await client.connect();
  try {
    await emit(client, config);
  } finally {
    await client.end();
  }
}

main().catch(err => { console.error(err); process.exit(1); });

async function emit(client: Client, config: Config) {
  const { rows: tables } = await client.query<{ table_name: string; has_tenant_id: boolean }>(`
    SELECT t.table_name,
           EXISTS (SELECT 1 FROM information_schema.columns c
                   WHERE c.table_schema = t.table_schema AND c.table_name = t.table_name
                     AND c.column_name = 'tenant_id') AS has_tenant_id
    FROM information_schema.tables t
    WHERE t.table_schema = 'public' AND t.table_type = 'BASE TABLE'
    ORDER BY t.table_name
  `);

  console.log('-- Auto-generated RLS hardening block. Review before committing.');
  console.log('-- Generated by scripts/generate-rls-audit-migration.ts');
  console.log();

  for (const { table_name, has_tenant_id } of tables) {
    const override = config.overrides[table_name];
    let category: string;
    if (override?.category === 'skip') {
      console.log(`-- SKIP ${table_name}: ${override.reason ?? 'per config'}`);
      continue;
    }
    if (override?.category) {
      category = override.category;
    } else if (has_tenant_id) {
      category = 'T';
    } else {
      console.error(`UNCATEGORIZED: ${table_name}. Add to rls-audit-config.yaml.`);
      process.exit(2);
    }
    emitPolicyBlock(table_name, category);
  }
}

function emitPolicyBlock(table: string, category: string) {
  const q = (s: string) => `public.${s}`;
  console.log(`-- ${table} (category=${category})`);

  // Drop any existing anon-open policies
  console.log(`DO $$ DECLARE r RECORD; BEGIN
    FOR r IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename='${table}' LOOP
      EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', r.policyname, '${table}');
    END LOOP;
  END $$;`);

  if (category === 'T') {
    console.log(`CREATE POLICY "t_select_own" ON ${q(table)} FOR SELECT TO authenticated
      USING (tenant_id = _resolve_tenant_id());
CREATE POLICY "t_insert_own" ON ${q(table)} FOR INSERT TO authenticated
  WITH CHECK (tenant_id = _resolve_tenant_id() AND _guard_expiry_write() IS NULL);
CREATE POLICY "t_update_own" ON ${q(table)} FOR UPDATE TO authenticated
  USING (tenant_id = _resolve_tenant_id())
  WITH CHECK (tenant_id = _resolve_tenant_id() AND _guard_expiry_write() IS NULL);
CREATE POLICY "t_delete_own" ON ${q(table)} FOR DELETE TO authenticated
  USING (tenant_id = _resolve_tenant_id() AND _guard_expiry_write() IS NULL);
ALTER TABLE ${q(table)} ENABLE ROW LEVEL SECURITY;
ALTER TABLE ${q(table)} FORCE ROW LEVEL SECURITY;
REVOKE ALL ON ${q(table)} FROM anon, PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON ${q(table)} TO authenticated;`);
  } else if (category === 'P') {
    console.log(`CREATE POLICY "p_platform_admin_only" ON ${q(table)} FOR ALL TO authenticated
  USING (public._is_platform_admin_from_jwt())
  WITH CHECK (public._is_platform_admin_from_jwt());
ALTER TABLE ${q(table)} ENABLE ROW LEVEL SECURITY;
ALTER TABLE ${q(table)} FORCE ROW LEVEL SECURITY;
REVOKE ALL ON ${q(table)} FROM anon, PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON ${q(table)} TO authenticated;`);
  } else if (category === 'G') {
    console.log(`CREATE POLICY "g_read_all" ON ${q(table)} FOR SELECT TO authenticated USING (true);
ALTER TABLE ${q(table)} ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON ${q(table)} FROM anon, PUBLIC;
GRANT SELECT ON ${q(table)} TO authenticated;`);
  } else if (category === 'A') {
    // tenant_users specific template (only one A table for now)
    console.log(`CREATE POLICY "a_self_or_tenant_admin" ON ${q(table)} FOR SELECT TO authenticated
  USING (
    user_id = auth.uid()
    OR (tenant_id = _resolve_tenant_id()
        AND EXISTS (SELECT 1 FROM public.tenant_users me
                    WHERE me.tenant_id = ${q(table)}.tenant_id
                      AND me.user_id = auth.uid()
                      AND me.role IN ('owner','admin')))
  );
CREATE POLICY "a_admin_write" ON ${q(table)} FOR ALL TO authenticated
  USING (tenant_id = _resolve_tenant_id()
         AND EXISTS (SELECT 1 FROM public.tenant_users me
                     WHERE me.tenant_id = ${q(table)}.tenant_id
                       AND me.user_id = auth.uid()
                       AND me.role IN ('owner','admin')))
  WITH CHECK (tenant_id = _resolve_tenant_id());
ALTER TABLE ${q(table)} ENABLE ROW LEVEL SECURITY;
ALTER TABLE ${q(table)} FORCE ROW LEVEL SECURITY;
REVOKE ALL ON ${q(table)} FROM anon, PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON ${q(table)} TO authenticated;`);
  }
  console.log();
}
