-- 20261115000211_warehouse_transfers_schema.sql
-- Two-step warehouse transfer parent + child tables + doc-number sequence.
-- Full spec: §4.1, §4.2, §6.

BEGIN;

-- ─── warehouse_transfers (parent) ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.warehouse_transfers (
  tenant_id            uuid        NOT NULL,
  id                   bigint      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  doc_no               text        NOT NULL,
  from_warehouse_id    uuid        NOT NULL REFERENCES public.warehouses(id),
  to_warehouse_id      uuid        NOT NULL REFERENCES public.warehouses(id),
  sender_user_id       uuid        NOT NULL REFERENCES auth.users(id),
  receiver_user_id     uuid        NOT NULL REFERENCES auth.users(id),
  status               text        NOT NULL DEFAULT 'IN_TRANSIT',
  notes                text        NULL,
  client_request_id    text        NULL,
  initiated_at         timestamptz NOT NULL DEFAULT now(),
  received_at          timestamptz NULL,
  received_by_user_id  uuid        NULL REFERENCES auth.users(id),
  cancelled_at         timestamptz NULL,
  cancelled_by_user_id uuid        NULL REFERENCES auth.users(id),
  cancel_reason        text        NULL,
  total_qty_sent       int         NOT NULL,
  total_qty_received   int         NULL,
  total_loss_qty       int         NULL,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, id),
  UNIQUE (tenant_id, doc_no),
  UNIQUE (tenant_id, client_request_id),
  CHECK (from_warehouse_id <> to_warehouse_id),
  CHECK (status IN ('IN_TRANSIT','RECEIVED','PARTIAL','CANCELLED')),
  CHECK (total_qty_sent > 0),
  CHECK (
    (status = 'IN_TRANSIT' AND received_at IS NULL AND cancelled_at IS NULL) OR
    (status IN ('RECEIVED','PARTIAL') AND received_at IS NOT NULL AND cancelled_at IS NULL) OR
    (status = 'CANCELLED' AND cancelled_at IS NOT NULL AND received_at IS NULL)
  ),
  CHECK (
    (status = 'RECEIVED' AND total_qty_received = total_qty_sent AND total_loss_qty IS NULL) OR
    (status = 'PARTIAL'  AND total_qty_received < total_qty_sent AND total_loss_qty = total_qty_sent - total_qty_received AND total_qty_received >= 0) OR
    (status IN ('IN_TRANSIT','CANCELLED') AND total_qty_received IS NULL AND total_loss_qty IS NULL)
  )
);

CREATE INDEX IF NOT EXISTS warehouse_transfers_tenant_status_to
  ON public.warehouse_transfers (tenant_id, to_warehouse_id, status)
  WHERE status = 'IN_TRANSIT';

CREATE INDEX IF NOT EXISTS warehouse_transfers_tenant_initiated_at
  ON public.warehouse_transfers (tenant_id, initiated_at DESC);

CREATE INDEX IF NOT EXISTS warehouse_transfers_receiver_pending
  ON public.warehouse_transfers (tenant_id, receiver_user_id, status)
  WHERE status = 'IN_TRANSIT';

-- ─── warehouse_transfer_items (child) ────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.warehouse_transfer_items (
  tenant_id        uuid   NOT NULL,
  transfer_id      bigint NOT NULL,
  line_no          int    NOT NULL,
  sku              text   NOT NULL REFERENCES public.stocks(sku),
  qty_sent         int    NOT NULL CHECK (qty_sent > 0),
  qty_received     int    NULL CHECK (qty_received >= 0),
  loss_qty         int    NULL CHECK (loss_qty >= 0),
  loss_movement_id bigint NULL,
  PRIMARY KEY (tenant_id, transfer_id, line_no),
  FOREIGN KEY (tenant_id, transfer_id) REFERENCES public.warehouse_transfers (tenant_id, id) ON DELETE CASCADE,
  CHECK (qty_received IS NULL OR qty_received <= qty_sent),
  CHECK (
    (qty_received IS NULL AND loss_qty IS NULL) OR
    (qty_received = qty_sent AND loss_qty IS NULL) OR
    (qty_received < qty_sent AND loss_qty = qty_sent - qty_received)
  )
);

CREATE INDEX IF NOT EXISTS warehouse_transfer_items_sku
  ON public.warehouse_transfer_items (tenant_id, sku);

CREATE INDEX IF NOT EXISTS warehouse_transfer_items_transfer
  ON public.warehouse_transfer_items (tenant_id, transfer_id);

-- ─── warehouse_transfer_doc_seq (per-tenant per-month sequence) ──────────
CREATE TABLE IF NOT EXISTS public.warehouse_transfer_doc_seq (
  tenant_id uuid NOT NULL,
  year      int  NOT NULL,
  month     int  NOT NULL CHECK (month BETWEEN 1 AND 12),
  seq       int  NOT NULL DEFAULT 0,
  PRIMARY KEY (tenant_id, year, month)
);

-- Helper: allocate next doc_no for (tenant_id, current year, current month).
-- Returns padded 3-digit sequence string (TR-YYYY-MM-NNN caller-formatted).
CREATE OR REPLACE FUNCTION public._next_warehouse_transfer_doc_no(p_tenant_id uuid)
RETURNS text
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_year int := EXTRACT(YEAR  FROM now())::int;
  v_month int := EXTRACT(MONTH FROM now())::int;
  v_seq int;
BEGIN
  INSERT INTO public.warehouse_transfer_doc_seq (tenant_id, year, month, seq)
  VALUES (p_tenant_id, v_year, v_month, 1)
  ON CONFLICT (tenant_id, year, month) DO UPDATE
    SET seq = warehouse_transfer_doc_seq.seq + 1
  RETURNING seq INTO v_seq;

  RETURN format('TR-%s-%s-%s', v_year, lpad(v_month::text, 2, '0'), lpad(v_seq::text, 3, '0'));
END;
$$;

REVOKE ALL ON FUNCTION public._next_warehouse_transfer_doc_no(uuid) FROM PUBLIC, anon, authenticated;
-- Called only from other SECDEF RPCs (initiate). No direct grant.

COMMIT;
